In [1]:
print("Welcome to the bootcamp")

Welcome to the bootcamp


In [3]:
print("Hello World")

Hello World


In [9]:
#numpy
lst=[1,2,3,4,5,6,7,8,9]

In [13]:
%timeit [i ** 2 for i in lst]

3.87 µs ± 401 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [12]:
!pip install numpy


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [19]:
import numpy as np
arr= np.array(lst)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
%timeit arr ** 2

568 ns ± 17.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [23]:
import numpy as np
arr= np.log(lst)
arr

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [25]:
%timeit arr ** 2

946 ns ± 425 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [30]:
arr1 = np.random.randint (10,100,size =(5,6))

arr1

array([[47, 95, 87, 89, 42, 18],
       [81, 97, 25, 64, 10, 67],
       [64, 62, 91, 78, 15, 52],
       [33, 80, 16, 75, 74, 43],
       [89, 80, 50, 44, 55, 99]])

In [32]:
!pip install pandas


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [39]:
import pandas as pd
df = pd.DataFrame(data = arr1)

#print the data
df

0   1   2   3   4   5
0  47  95  87  89  42  18
1  81  97  25  64  10  67
2  64  62  91  78  15  52
3  33  80  16  75  74  43
4  89  80  50  44  55  99