In [ ]:
print("Welcome to the bootcamp")

Welcome to the bootcamp


In [1]:
print("hello shrushti")

hello shrushti


In [6]:
#numpy
lst = [1,2,3,4,5,6,7,8,9]
%timeit [i** 2 for i in lst]

2.65 µs ± 21.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [2]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [9]:
import numpy as np
arr = np.array(lst)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
%timeit arr**2

786 ns ± 277 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [13]:
arrl = np.random.randint(10,100, size = (5,6))
#print arrl
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
!pip install pandas




In [ ]:
array([[44,82,20,82,44,77],
       [14,50,61,70,85,12],
       [24,62,63,32,85,39,],
       [22,58,32,93,33,54]])

In [17]:
import pandas as pd
df = pd.DataFrame(data = arrl)
#print this data
df


0   1   2   3   4   5
0  30  18  97  82  52  88
1  46  99  12  56  52  25
2  45  41  38  31  67  76
3  32  81  12  25  42  47
4  26  37  21  75  67  28