In [2]:
print("Welcome to the bootcamp")

Welcome to the bootcamp


In [1]:
print("Hello Dev")

Hello Dev


In [3]:
#numpy
lis=[1,2,3,4,5,6,7,8,9]

In [4]:
%timeit [i ** 2 for i in lis]

2.66 µs ± 99.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [7]:
import numpy as np
arr=np.array(lis)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
%timeit arr ** 2

594 ns ± 10.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [9]:
arr1=np.random.randint(10,100,size=(5,6))
print(arr1)

[[91 46 86 51 20 95]
 [55 32 70 38 58 67]
 [99 73 18 94 12 36]
 [11 11 25 36 83 42]
 [71 42 15 12 72 52]]


In [11]:
!pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [12]:
import pandas as pd

In [13]:
df=pd.DataFrame(data=arr1)
df

0   1   2   3   4   5
0  91  46  86  51  20  95
1  55  32  70  38  58  67
2  99  73  18  94  12  36
3  11  11  25  36  83  42
4  71  42  15  12  72  52