In [ ]:
print("Welcome to the bootcamp")

Welcome to the bootcamp


In [1]:
print("hello developers")

hello developers


In [4]:
#numpy
list = [1,2,3,4,5,6,7,8,9]

In [5]:
%timeit [i ** 2 for i in list]

2.63 µs ± 37.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [7]:
import numpy as np

In [9]:
arr = np.array(list)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
%timeit arr ** 2

570 ns ± 9.04 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [12]:
arr1 = np.random.randint(10,100, size = (5,6))
arr1


array([[80, 10, 28, 88, 90, 77],
       [59, 10, 77, 47, 21, 88],
       [57, 33, 93, 70, 34, 43],
       [62, 21, 20, 15, 59, 51],
       [90, 84, 60, 93, 13, 28]])

In [13]:
!pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [14]:
import pandas as pd


In [15]:
df = pd.DataFrame(data = arr1)
arr1

array([[80, 10, 28, 88, 90, 77],
       [59, 10, 77, 47, 21, 88],
       [57, 33, 93, 70, 34, 43],
       [62, 21, 20, 15, 59, 51],
       [90, 84, 60, 93, 13, 28]])

In [16]:
df

0   1   2   3   4   5
0  80  10  28  88  90  77
1  59  10  77  47  21  88
2  57  33  93  70  34  43
3  62  21  20  15  59  51
4  90  84  60  93  13  28