In [ ]:
print("Welcome to the bootcamp")

Welcome to the bootcamp


In [1]:
print("hello developers")

hello developers


In [2]:
lst = [1,2,3,4,5,6,7,8,9]

In [4]:
%timeit [i**2 for i in lst]

2.49 µs ± 40.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [8]:
import numpy as np

arr = np.array(lst)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
%timeit arr**2

545 ns ± 11 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [10]:
arr**2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [11]:
arr1 = np.random.randint(10,100, size = (5,6))
arr1

array([[32, 84, 45, 77, 56, 83],
       [87, 58, 44, 94, 26, 20],
       [32, 14, 65, 99, 63, 65],
       [52, 85, 21, 36, 35, 81],
       [63, 11, 70, 33, 54, 29]])

In [12]:
import pandas as pd

In [15]:
df = pd.DataFrame(data = arr1)
df

0   1   2   3   4   5
0  32  84  45  77  56  83
1  87  58  44  94  26  20
2  32  14  65  99  63  65
3  52  85  21  36  35  81
4  63  11  70  33  54  29